# Generated by Django 2.1.7 on 2019-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('ImageURL', models.CharField(max_length=500)),
            ],
        ),
    ]
