# Generated by Django 2.1.7 on 2019-04-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Posts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
